name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 13 * * 1"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PIXI_VERSION: "v0.63.0"

permissions: {}

jobs:
  cache-pixi-lock:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    outputs:
      cache-key: ${{ steps.pixi-lock.outputs.cache-key }}
      pixi-version: ${{ steps.pixi-lock.outputs.pixi-version }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: Parcels-code/pixi-lock/create-and-cache@a9aee67fa67426e6b0297fa5bef80600572be153
        id: pixi-lock
        with:
          pixi-version: ${{env.PIXI_VERSION}}
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: pixi-lock
          path: pixi.lock
  test:
    name: Test (${{ matrix.pixi-env }})
    needs: ["cache-pixi-lock"]
    if: github.repository == 'xgcm/xgcm'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        pixi-env:
          - test-latest
          - test-minimum
          - test-py311
          - test-core
          - test-nightly
    env:
      PIXI_ENV: ${{ matrix.pixi-env }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Restore cached pixi lockfile
        uses: Parcels-code/pixi-lock/restore@a9aee67fa67426e6b0297fa5bef80600572be153
        with:
          cache-key: ${{ needs.cache-pixi-lock.outputs.cache-key }}

      - uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
        with:
          pixi-version: ${{ needs.cache-pixi-lock.outputs.pixi-version }}
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
      - name: Run Tests
        run: |
          pixi run -e ${{matrix.pixi-env}} tests --cov=./ --cov-report=xml
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: PIXI_ENV
          name: codecov-umbrella
          fail_ci_if_error: false

  zizmor:
    name: GHA Security Analysis using Zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
