name: Build and Upload xGCM to PyPI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - published

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'xgcm/xgcm'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools setuptools-scm build twine
      - name: Build only
        if: github.event_name != 'release'
        run: |
          python -m build
          twine check dist/*
      - name: Build and publish
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m build
          twine check dist/*
          twine upload dist/*
